import type { Book, Category } from './types';

export const categories: Category[] = [
  { name: 'Novels', slug: 'novels' },
  { name: 'Poetry', slug: 'poetry' },
  { name: 'History', slug: 'history' },
  { name: 'Children\'s Books', slug: 'childrens-books' },
  { name: 'Biographies', slug: 'biographies' },
  { name: 'Drama', slug: 'drama' },
  { name: 'Essays', slug: 'essays' },
];

export const books: Book[] = [
  {
    id: 'chemmeen',
    title: 'Chemmeen',
    authors: ['Thakazhi Sivasankara Pillai'],
    year: 1956,
    description: 'A poignant tale of love, loss, and tradition set in a coastal fishing village in Kerala. The novel explores the lives and beliefs of the fishermen community, revolving around the forbidden love between Karuthamma and Pareekutty.',
    categories: ['Novels', 'Drama'],
    formats: {
      pdf: '/books/chemmeen.pdf',
      epub: '/books/chemmeen.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 1052,
  },
  {
    id: 'pathummayude-aadu',
    title: 'Pathummayude Aadu',
    authors: ['Vaikom Muhammad Basheer'],
    year: 1959,
    description: 'A humorous and autobiographical work that revolves around the chaos of Basheer\'s household, including his family members and a goat named Pathumma. It\'s a classic of Malayalam literature known for its simple language and wit.',
    categories: ['Novels', 'Children\'s Books'],
    formats: {
      pdf: '/books/pathummayude-aadu.pdf',
      epub: '/books/pathummayude-aadu.epub',
      mp3: '/audio/pathummayude-aadu.mp3',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 1890,
  },
  {
    id: 'indulekha',
    title: 'Indulekha',
    authors: ['O. Chandu Menon'],
    year: 1889,
    description: 'Considered the first modern novel in Malayalam, Indulekha is a story of a beautiful and educated Nair woman and her love for Madhavan. The novel critiques the feudal system and traditional customs of the time.',
    categories: ['Novels', 'History'],
    formats: {
      pdf: '/books/indulekha.pdf',
      epub: '/books/indulekha.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 876,
  },
  {
    id: 'ramanan',
    title: 'Ramanan',
    authors: ['Changampuzha Krishna Pillai'],
    year: 1936,
    description: 'A pastoral elegy that tells the tragic love story of two shepherds, Ramanan and Chandrika. It became immensely popular and is a landmark work in Malayalam romantic poetry.',
    categories: ['Poetry', 'Drama'],
    formats: {
      pdf: '/books/ramanan.pdf',
      epub: '/books/ramanan.epub',
      mp3: '/audio/ramanan.mp3',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 1234,
  },
  {
    id: 'khasakkinte-ithihasam',
    title: 'Khasakkinte Ithihasam',
    authors: ['O. V. Vijayan'],
    year: 1969,
    description: 'A complex and layered novel that follows Ravi, who arrives in the remote village of Khasak, and delves into the myths, legends, and lives of its inhabitants. It is a landmark of modernist literature in Malayalam.',
    categories: ['Novels', 'Essays'],
    formats: {
      pdf: '/books/khasakkinte-ithihasam.pdf',
      epub: '/books/khasakkinte-ithihasam.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 950,
  },
  {
    id: 'oru-sankeerthanam-pole',
    title: 'Oru Sankeerthanam Pole',
    authors: ['Perumbadavam Sreedharan'],
    year: 1993,
    description: 'A fictionalized account of 21 days in the life of Fyodor Dostoevsky, focusing on his relationship with his stenographer Anna and his struggles with debt and epilepsy while writing "The Gambler".',
    categories: ['Novels', 'Biographies'],
    formats: {
      pdf: '/books/oru-sankeerthanam-pole.pdf',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 750,
  },
  {
    id: 'aithihyamala',
    title: 'Aithihyamala',
    authors: ['Kottarathil Sankunni'],
    year: 1909,
    description: 'A collection of centuries of legends and folklore from Kerala, covering a wide range of subjects from famous personalities and temples to sorcerers and elephants. It is a treasure trove of Kerala culture.',
    categories: ['History', 'Children\'s Books', 'Essays'],
    formats: {
      pdf: '/books/aithihyamala.pdf',
      epub: '/books/aithihyamala.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PENDING',
    downloads: 1500,
  },
  {
    id: 'mayyazhippuzhayude-theerangalil',
    title: 'Mayyazhippuzhayude Theerangalil',
    authors: ['M. Mukundan'],
    year: 1974,
    description: 'Set in the former French colony of Mahé (Mayyazhi), this novel captures the political and social turmoil of the region as it transitions from French rule to integration with India.',
    categories: ['Novels', 'History'],
    formats: {
      pdf: '/books/mayyazhippuzhayude-theerangalil.pdf',
      epub: '/books/mayyazhippuzhayude-theerangalil.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PENDING',
    downloads: 820,
  },
];
