
import type { Book, Category } from './types';

export const categories: Category[] = [
  { name: 'Novels', slug: 'novels' },
  { name: 'Poetry', slug: 'poetry' },
  { name: 'History', slug: 'history' },
  { name: 'Children\'s Books', slug: 'childrens-books' },
  { name: 'Biographies', slug: 'biographies' },
  { name: 'Drama', slug: 'drama' },
  { name: 'Essays', slug: 'essays' },
];

export const books: Book[] = [
  {
    id: 'chemmeen',
    title: 'Chemmeen',
    authors: ['Thakazhi Sivasankara Pillai'],
    year: 1956,
    description: 'A poignant tale of love, loss, and tradition set in a coastal fishing village in Kerala. The novel explores the lives and beliefs of the fishermen community, revolving around the forbidden love between Karuthamma and Pareekutty.',
    categories: ['Novels', 'Drama'],
    formats: {
      pdf: '/books/chemmeen.pdf',
      epub: '/books/chemmeen.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 1052,
  },
  {
    id: 'pathummayude-aadu',
    title: 'Pathummayude Aadu',
    authors: ['Vaikom Muhammad Basheer'],
    year: 1959,
    description: 'A humorous and autobiographical work that revolves around the chaos of Basheer\'s household, including his family members and a goat named Pathumma. It\'s a classic of Malayalam literature known for its simple language and wit.',
    categories: ['Novels', 'Children\'s Books'],
    formats: {
      pdf: '/books/pathummayude-aadu.pdf',
      epub: '/books/pathummayude-aadu.epub',
      mp3: '/audio/pathummayude-aadu.mp3',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 1890,
  },
  {
    id: 'indulekha',
    title: 'Indulekha',
    authors: ['O. Chandu Menon'],
    year: 1889,
    description: 'Considered the first modern novel in Malayalam, Indulekha is a story of a beautiful and educated Nair woman and her love for Madhavan. The novel critiques the feudal system and traditional customs of the time.',
    categories: ['Novels', 'History'],
    formats: {
      pdf: '/books/indulekha.pdf',
      epub: '/books/indulekha.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 876,
  },
  {
    id: 'ramanan',
    title: 'Ramanan',
    authors: ['Changampuzha Krishna Pillai'],
    year: 1936,
    description: 'A pastoral elegy that tells the tragic love story of two shepherds, Ramanan and Chandrika. It became immensely popular and is a landmark work in Malayalam romantic poetry.',
    categories: ['Poetry', 'Drama'],
    formats: {
      pdf: '/books/ramanan.pdf',
      epub: '/books/ramanan.epub',
      mp3: '/audio/ramanan.mp3',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 1234,
  },
  {
    id: 'khasakkinte-ithihasam',
    title: 'Khasakkinte Ithihasam',
    authors: ['O. V. Vijayan'],
    year: 1969,
    description: 'A complex and layered novel that follows Ravi, who arrives in the remote village of Khasak, and delves into the myths, legends, and lives of its inhabitants. It is a landmark of modernist literature in Malayalam.',
    categories: ['Novels', 'Essays'],
    formats: {
      pdf: '/books/khasakkinte-ithihasam.pdf',
      epub: '/books/khasakkinte-ithihasam.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 950,
  },
    {
    id: 'balyakalasakhi',
    title: 'Balyakalasakhi',
    authors: ['Vaikom Muhammad Basheer'],
    year: 1944,
    description: 'A tragic love story between Majeed and Suhra, childhood friends. The novel is one of the most famous works by Basheer and is celebrated for its poignant narrative.',
    categories: ['Novels', 'Drama'],
    formats: {
      pdf: '/books/balyakalasakhi.pdf',
      epub: '/books/balyakalasakhi.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 980,
  },
  {
    id: 'randamoozham',
    title: 'Randamoozham',
    authors: ['M. T. Vasudevan Nair'],
    year: 1984,
    description: 'The story of the Mahabharata retold from the perspective of Bhima, the second Pandava. It is a powerful and insightful take on the epic, focusing on Bhima\'s thoughts and feelings.',
    categories: ['Novels', 'History', 'Essays'],
    formats: {
      pdf: '/books/randamoozham.pdf',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Copyrighted',
    is_public_domain: false,
    status: 'PUBLISHED',
    downloads: 2100,
  },
  {
    id: 'aadujeevitham',
    title: 'Aadujeevitham',
    authors: ['Benyamin'],
    year: 2008,
    description: 'Based on a true story, this novel follows Najeeb, an Indian migrant worker who finds himself stranded in the Saudi Arabian desert, forced to live a slave-like existence herding goats.',
    categories: ['Novels', 'Biographies'],
    formats: {
      epub: '/books/aadujeevitham.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Copyrighted',
    is_public_domain: false,
    status: 'PUBLISHED',
    downloads: 1745,
  },
  {
    id: 'oru-sankeerthanam-pole',
    title: 'Oru Sankeerthanam Pole',
    authors: ['Perumbadavam Sreedharan'],
    year: 1993,
    description: 'A fictionalized account of 21 days in the life of Fyodor Dostoevsky, focusing on his relationship with his stenographer Anna and his struggles with debt and epilepsy while writing "The Gambler".',
    categories: ['Novels', 'Biographies'],
    formats: {
      pdf: '/books/oru-sankeerthanam-pole.pdf',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 750,
  },
  {
    id: 'aithihyamala',
    title: 'Aithihyamala',
    authors: ['Kottarathil Sankunni'],
    year: 1909,
    description: 'A collection of centuries of legends and folklore from Kerala, covering a wide range of subjects from famous personalities and temples to sorcerers and elephants. It is a treasure trove of Kerala culture.',
    categories: ['History', 'Children\'s Books', 'Essays'],
    formats: {
      pdf: '/books/aithihyamala.pdf',
      epub: '/books/aithihyamala.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PENDING',
    downloads: 1500,
  },
  {
    id: 'mayyazhippuzhayude-theerangalil',
    title: 'Mayyazhippuzhayude Theerangalil',
    authors: ['M. Mukundan'],
    year: 1974,
    description: 'Set in the former French colony of Mahé (Mayyazhi), this novel captures the political and social turmoil of the region as it transitions from French rule to integration with India.',
    categories: ['Novels', 'History'],
    formats: {
      pdf: '/books/mayyazhippuzhayude-theerangalil.pdf',
      epub: '/books/mayyazhippuzhayude-theerangalil.epub',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PENDING',
    downloads: 820,
  },
  {
    id: 'yakshi',
    title: 'Yakshi',
    authors: ['Malayattoor Ramakrishnan'],
    year: 1967,
    description: 'A psychological thriller that explores the mind of a college lecturer, Sreenivasan, who suffers a disfiguring accident and becomes entangled with a mysterious and beautiful woman named Ragini, who he suspects might be a "yakshi" (a mythical vampire).',
    categories: ['Novels', 'Drama'],
    formats: {},
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 650,
  },
  {
    id: 'naalukettu',
    title: 'Naalukettu',
    authors: ['M. T. Vasudevan Nair'],
    year: 1958,
    description: 'A powerful novel centered on Appunni, a young boy who grows up in a disintegrating matrilineal Nair "tharavadu" (ancestral home). The story follows his quest for identity and revenge against the man he believes is responsible for his family\'s downfall.',
    categories: ['Novels', 'History'],
    formats: {
      pdf: '/books/naalukettu.pdf',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Copyrighted',
    is_public_domain: false,
    status: 'PUBLISHED',
    downloads: 1320,
  },
  {
    id: 'kayar',
    title: 'Kayar',
    authors: ['Thakazhi Sivasankara Pillai'],
    year: 1978,
    description: 'A magnum opus that chronicles the lives of several generations in a Kerala village over two and a half centuries. The novel documents the evolution of the society, its customs, and the land ownership system through the lives of its diverse characters.',
    categories: ['Novels', 'History', 'Essays'],
    formats: {},
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 550,
  },
  {
    id: 'marthandavarma',
    title: 'Marthandavarma',
    authors: ['C. V. Raman Pillai'],
    year: 1891,
    description: 'A historical romance novel that narrates the story of Anizham Thirunal Marthanda Varma, the founder of the Travancore kingdom in the 18th century. It is a tale of chivalry, conspiracy, and patriotism.',
    categories: ['Novels', 'History'],
    formats: {
      pdf: 'https://archive.org/details/marthandavarma00ramapillai',
      epub: 'https://www.gutenberg.org/ebooks/67781',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Project Gutenberg / Internet Archive',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 430,
  },
  {
    id: 'ente-uppuppakkoranendarnnu',
    title: 'Ente Uppuppakkoranendarnnu',
    authors: ['Vaikom Muhammad Basheer'],
    year: 1951,
    description: 'A story that criticizes the prejudices and insular attitudes of a bygone era through the eyes of Kunjupathumma and her daughter. The title, which translates to "My Grandfather Had an Elephant," satirizes the empty pride of feudal families.',
    categories: ['Novels', 'Children\'s Books'],
    formats: {
      pdf: '/books/ente-uppuppakkoranendarnnu.pdf',
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 1150,
  },
  {
    id: 'aranyakam',
    title: 'Aranyakam',
    authors: ['Bibhutibhushan Bandyopadhyay'],
    year: 1939,
    description: 'Though originally in Bengali, its Malayalam translation is widely read. A classic novel that depicts the life of Satyacharan, who takes up a job as a manager of a huge forest estate in Bihar and his deep connection with nature.',
    categories: ['Novels', 'Essays'],
    formats: {
      epub: '/books/aranyakam.epub'
    },
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PUBLISHED',
    downloads: 320,
  },
  {
    id: 'karutha-thambratti',
    title: 'Karutha Thambratti',
    authors: ['C. V. Raman Pillai'],
    year: 1913,
    description: 'This is the second historical novel by C.V. Raman Pillai, known for its intricate plot and character development within the context of Travancore\'s history.',
    categories: ['Novels', 'History'],
    formats: {},
    cover_url: 'https://placehold.co/400x600.png',
    source: 'Public Domain',
    is_public_domain: true,
    status: 'PENDING',
    downloads: 150,
  }
];
